#/bin/bash

if [ ! -n "$WERCKER_HUGO_BUILD_BIN" ]; then
    export WERCKER_HUGO_BUILD_BIN=bin/hugo-linux
fi

if [ ! -n "$WERCKER_HUGO_BUILD_FLAGS" ]; then
    WERCKER_HUGO_BUILD_FLAGS=""
fi
if [ -n "$WERCKER_HUGO_BUILD_THEME" ]; then
    WERCKER_HUGO_BUILD_FLAGS=$WERCKER_HUGO_BUILD_FLAGS" --theme="${WERCKER_HUGO_BUILD_THEME}
fi

${WERCKER_SOURCE_DIR}/${WERCKER_HUGO_BUILD_BIN} --source="${WERCKER_SOURCE_DIR}" ${WERCKER_HUGO_BUILD_FLAGS}
